---
core-mx:
    hostname: 100.64.99.5
    username: wquizhpi
    platform: junos
    password: Juniper
    groups:
      - junos_group

edge-switch:
    hostname: 100.64.0.4
    username: wquizhpi
    platform: ios
    password: cisco
    groups:
      - ios_group

ios-router:
    hostname: 100.64.99.128
    username: wquizhpi
    platform: ios
    password: cisco
    groups:
      - ios_group

leaf1:
    hostname: 100.64.99.2
    username: wquizhpi
    platform: junos
    password: Juniper
    groups:
      - junos_group

leaf2:
    hostname: 100.64.99.3
    username: wquizhpi
    platform: junos
    password: Juniper
    groups:
      - junos_group

leaf3:
    hostname: 100.64.99.4
    username: wquizhpi
    platform: junos
    password: Juniper
    groups:
      - junos_group

spine1:
    hostname: 100.64.99.0
    username: wquizhpi
    platform: junos
    password: Juniper
    groups:
      - junos_group

spine2:
    hostname: 100.64.99.1
    username: wquizhpi
    platform: junos
    password: Juniper
    groups:
      - junos_group
