---
sw1:
    hostname: 100.64.0.4
    platform: ios
    username: {}
    password: {}
    groups:
      - ios_group

sw2:
    hostname: 100.64.99.128
    platform: ios
    username: {}
    password: {}
    groups:
      - ios_group
