---
sw1:
    hostname: 100.64.0.4
    platform: ios
    username: wquizhpi
    password: cisco
    groups:
      - ios_group

sw2:
    hostname: 100.64.99.128
    platform: ios
    username: wquizhpi
    password: cisco
    groups:
      - ios_group
